name: Sauvegarde automatique du dépôt
#Vaglio lisa/ Abry maxime/ Simon Théo/ Demeulenaere Bastien/ Eglof batiste
on:
  schedule:
    - cron: '* * * * *' # Exécute toutes les minutes

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v2

      - name: Créer une archive du dépôt
        run: tar czf backup.tar.gz .

      - name: Envoyer l'archive vers un service de stockage
        uses: actions/upload-artifact@v2
        with:
          name: backup
          path: backup.tar.gz
