name: VerifLienADE

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v2

      - name: Configurer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Exécuter le script Python
        id: run_script
        run: python ../verif_lien_ade.py 

      - name: Vérifier le résultat
        run: |
          result=$(echo "${{ steps.run_script.outputs.stdout }}")
          if [ "$result" == "True" ]; then
            echo "Le résultat est True. Tout va bien !"
          else
            echo "Le résultat est différent de True. Il y a peut-être un problème."
            exit 1
          fi
